@echo off
set temp=%~dp0
echo @echo off > "%tmp%\gitauto.bat"
echo set workingDirectory=%temp:~0,-1% >> "%tmp%\gitauto.bat"
echo cd /D %%workingDirectory%% >> "%tmp%\gitauto.bat"
echo if "%%1" EQU "pull" ( goto pulled_from_cmd ) >> "%tmp%\gitauto.bat"
echo title gitauto >> "%tmp%\gitauto.bat"
echo cls >> "%tmp%\gitauto.bat"
echo echo program uruchomiony z: %%workingDirectory%% >> "%tmp%\gitauto.bat"
echo set fileName=*>> "%tmp%\gitauto.bat"
echo echo. >> "%tmp%\gitauto.bat"
echo echo Chcesz pobra† najnowsze dane z repozytorium   (1)? >> "%tmp%\gitauto.bat"
echo echo Czy wysˆa† swoje pliki do niego               (2)? >> "%tmp%\gitauto.bat"
echo choice /C 12 /N /M "[1/2]:" >> "%tmp%\gitauto.bat"
echo. >> "%tmp%\gitauto.bat"
echo if %%ERRORLEVEL%% EQU 1 goto pull >> "%tmp%\gitauto.bat"
echo if %%ERRORLEVEL%% EQU 2 goto push_choice >> "%tmp%\gitauto.bat"
echo. >> "%tmp%\gitauto.bat"
echo :end >> "%tmp%\gitauto.bat"
echo echo. >> "%tmp%\gitauto.bat"
echo echo zakoäczono prace >> "%tmp%\gitauto.bat"
echo echo. >> "%tmp%\gitauto.bat"
echo pause >> "%tmp%\gitauto.bat"
echo exit >> "%tmp%\gitauto.bat"
echo. >> "%tmp%\gitauto.bat"
echo :pull >> "%tmp%\gitauto.bat"
echo echo. >> "%tmp%\gitauto.bat"
echo echo pobieram najnowsze wersje plik¢w... >> "%tmp%\gitauto.bat"
echo echo. >> "%tmp%\gitauto.bat"
echo git pull origin master >> "%tmp%\gitauto.bat"
echo goto end >> "%tmp%\gitauto.bat"
echo. >> "%tmp%\gitauto.bat"
echo :not_needed >> "%tmp%\gitauto.bat"
echo cls >> "%tmp%\gitauto.bat"
echo echo Nie ma potrzeby aktualizacji, wszystko aktualne >> "%tmp%\gitauto.bat"
echo goto end >> "%tmp%\gitauto.bat"
echo. >> "%tmp%\gitauto.bat"
echo :push_choice >> "%tmp%\gitauto.bat"
echo echo. >> "%tmp%\gitauto.bat"
echo echo Chcesz wysˆa†: >> "%tmp%\gitauto.bat"
echo echo WSZYSTKIE pliki kt¢re mog¥ zosta† zaktualizowane   (1)? >> "%tmp%\gitauto.bat"
echo echo jeden plik                                         (2)? >> "%tmp%\gitauto.bat"
echo echo tylko te oznaczone ju¾ jako do dodania             (3)? >> "%tmp%\gitauto.bat"
echo echo ju¾ zapisane commit'y                              (4)? >> "%tmp%\gitauto.bat"
echo choice /C 1234 /N /M "[1/2/3/4]:" >> "%tmp%\gitauto.bat"
echo if %%ERRORLEVEL%% EQU 1 goto push_add >> "%tmp%\gitauto.bat"
echo if %%ERRORLEVEL%% EQU 2 goto push_file >> "%tmp%\gitauto.bat"
echo if %%ERRORLEVEL%% EQU 3 goto push_commit >> "%tmp%\gitauto.bat"
echo if %%ERRORLEVEL%% EQU 4 goto push_only >> "%tmp%\gitauto.bat"
echo goto end >> "%tmp%\gitauto.bat"
echo. >> "%tmp%\gitauto.bat"
echo :push_file >> "%tmp%\gitauto.bat"
echo echo. >> "%tmp%\gitauto.bat"
echo set /P fileName=Podaj nazw© pliku:  >> "%tmp%\gitauto.bat"
echo goto push_add >> "%tmp%\gitauto.bat"
echo. >> "%tmp%\gitauto.bat"
echo :push_add >> "%tmp%\gitauto.bat"
echo echo. >> "%tmp%\gitauto.bat"
echo git add "%%fileName%%" >> "%tmp%\gitauto.bat"
echo :push_commit >> "%tmp%\gitauto.bat"
echo echo. >> "%tmp%\gitauto.bat"
echo set /P commit=Podaj commit tej aktualizacji:  >> "%tmp%\gitauto.bat"
echo echo. >> "%tmp%\gitauto.bat"
echo git commit -m "%%commit%%" >> "%tmp%\gitauto.bat"
echo :push_only >> "%tmp%\gitauto.bat"
echo git push origin master >> "%tmp%\gitauto.bat"
echo goto end >> "%tmp%\gitauto.bat"
echo. >> "%tmp%\gitauto.bat"
echo :pulled_from_cmd >> "%tmp%\gitauto.bat"
echo echo. >> "%tmp%\gitauto.bat"
echo echo pobieram najnowsze wersje plik¢w... >> "%tmp%\gitauto.bat"
echo echo. >> "%tmp%\gitauto.bat"
echo git pull origin master >> "%tmp%\gitauto.bat"
"%tmp%\gitauto.bat" %1 %2 %3 %4 %5 %6 %7 %8 %9